### PR TITLE
feat(integrations): add validation rules to salesforce fetch-fields

### PR DESCRIPTION
**Pull request by hassan254-prog**
## Describe your changes

- Small change to the salesforce fetch-fields action to also retrieve the validation rules.

## Issue ticket number and link
[EXT-148](https://linear.app/nango/issue/EXT-148/salesforce-investigation)
## Checklist before requesting a review (skip if just adding/editing APIs & templates)
- [x] I added tests, otherwise the reason is:
- [x] External API requests have `retries`
- [ ] Pagination is used where appropriate
- [ ] The built in `nango.paginate` call is used instead of a `while (true)` loop
- [ ] Third party requests are NOT parallelized (this can cause issues with rate limits)
- [ ] If a sync requires metadata the `nango.yaml` has `auto_start: false`
- [ ] If the sync is a `full` sync then `track_deletes: true` is set

### CODE REVIEW

**Comment by khaliqgant** [comment]
You should commit the mock files @hassan254-prog

**Comment by hassan254-prog** [comment]
> You should commit the mock files @hassan254-prog

Add mock data for the other syncs to ensure all tests pass.

**Comment by khaliqgant** [comment]
> > You should commit the mock files @hassan254-prog
> 
> Adding mock data for the other syncs to ensure all tests pass.

Thanks, looks like you need to save done the mock data again via the `--save-responses` flag @hassan254-prog

**Comment by hassan254-prog** [comment]
> > > You should commit the mock files @hassan254-prog
> > 
> > 
> > Adding mock data for the other syncs to ensure all tests pass.
> 
> Thanks, looks like you need to save done the mock data again via the `--save-responses` flag @hassan254-prog

I've placed it in draft mode to incorporate the new changes.

**Review by khaliqgant — APPROVED** [review]

**Pull request merged**
